sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vladmois/azureclient .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vladmois/azureclient
